### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [Kenwu2001/git-practice#1]
-  「代碼」 --> 程式碼，請盡量避免使用中國用語
-  「Branch大致上可以分成Master」現在的主分支還是用 master 嗎？

整體作業做得很好，希望你這學期都可以保持這樣的水平。

**Comment by Kenwu2001** [comment]
謝謝老師!!

**Comment by azole** [comment]
> 「Branch大致上可以分成Master」現在的主分支還是用 master 嗎？

沒有回覆我問題啊 XD

**Comment by Kenwu2001** [comment]
抱歉犯傻了。現在的主分支已經改成main了，查了一下是從2020年開始改變的，因為master這個字帶有歧視性。
以上，謝謝老師!

**Comment by azole** [comment]
yeap，謝謝回覆，那如果沒有其他要跟我討論的部分，這個 issue 就可以先關閉嚕。

**Comment by Kenwu2001** [comment]
OKOK目前沒有其他要討論的，那就先關閉了。
